### ISSUE TITLE
README refers to a missing `LICENSE` file

### ISSUE THREAD

**Issue by mbrukman** [wizenheimer/tinkerbird#7]
First of all, thank you for creating and sharing this project with us!

The README says this project is under the MIT license and refers to a `LICENSE` file:

https://github.com/wizenheimer/tinkerbird/blob/4c987b6380988e2eb53422c14ae8faf96056aa4a/README.md?plain=1#L231-L233

However, there's no `LICENSE` file in this repo.

Since you said it's MIT-licensed, please add a `LICENSE` file; you can use this MIT license template (the site is by GitHub): https://choosealicense.com/licenses/mit/ or you can use https://opensource.org/license/mit, but GitHub's site is providing an already properly formatted and word-wrapped text file template, which is easier to read, so I suggest using that one.

**Comment by wizenheimer** [comment]
Thanks for bringing this up. 
Would be pushing a fix.
